version: "3.8"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - kafka
      - redis

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  anomaly-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "kafka/consumers/anomaly.js"]
    depends_on:
      - kafka
      - redis

  logger-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "kafka/consumers/logger.js"]
    depends_on:
      - kafka

  redis-up-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "kafka/consumers/redis_up.js"]
    depends_on:
      - kafka
      - redis
